name: deploy-toy-website-end-to-end
concurrency: toy-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  #Build the application
  build:
    uses: itccbe/toy-website-end-to-end/.github/workflows/build.yml@main

  # Lint the Bicep file.
  lint:
    uses: itccbe/toy-website-end-to-end/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: itccbe/toy-website-end-to-end/.github/workflows/deploy.yml@main
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: ToyWebsiteTest
      reviewApiUrl: https://sandbox.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: itccbe/toy-website-end-to-end/.github/workflows/deploy.yml@main
    needs:
    - build
    - lint
    - deploy-test
    with:
      environmentType: Production
      resourceGroupName: ToyWebsiteProduction
      reviewApiUrl: https://api.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
